[package]
name = "git-cherry-branch"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
git2 = { version = "0.19.0", features = ["default", "vendored-openssl", "vendored-libgit2"]}
